[agent]
enable = true
name = "music"
description = "Search/play local music, set/increase/decrease system volume"
debug_exec = "target/release/music-agent"
exec = "music-agent"
is_server = true

# Play:
[actions.play]
enable = true
description = "Play local music by genre, artist, album and song options (prioritize using the artist argument)"

[actions.play.arguments]
genre = { type = "string", optional = true }
artist = { type = "string", optional = true }
album = { type = "string", optional = true }
song = { type = "string", optional = true }

[[actions.play.examples]]
query = "play rock genre"
data = { genre = "rock" }

[[actions.play.examples]]
query = "play Disturbed"
data = { artist = "Disturbed" }

[[actions.play.examples]]
query = "play Disturbed - The Sickness"
data = { artist = "Disturbed", album = "The Sickness" }

# Volume:
[actions.volume]
enable = true
description = "Set system volume by delta or force value"

[actions.volume.arguments]
delta = { type = "integer", optional = false }
force = { type = "boolean", description = "false by default", optional = true }

[[actions.volume.examples]]
query = "set volume to 50%"
data = { delta = 50, force = true }

[[actions.volume.examples]]
query = "increase volume by 20%"
data = { delta = 20 }

[[actions.volume.examples]]
query = "decrease volume by 30%"
data = { delta = -30 }

