[agent]
enable = true
name = "power"
description = "The system power control (with timeout): turnoff (poweroff), restart, suspend (sleep), lock session and cancel power operations."
debug_exec = "target/release/power-agent"
exec = "power-agent"
is_server = true

# Power:
[actions.power]
enable = true
description = "Power operation mode with timeout in seconds (always convert timeout to seconds)"

[actions.power.arguments]
mode = { type = "string", enum = ["turnoff", "restart", "suspend", "lock"], optional = false }
timeout = { type = "integer", optional = true }

[[actions.power.examples]]
query = "turnoff system after 30 secs"
data = { mode = "turnoff", timeout = 30 }

# Cancel:
[actions.cancel]
enable = true
description = "Cancel power operation"

[actions.cancel.arguments]
mode = { type = "string", optional = true }

[[actions.cancel.examples]]
query = "cancel turnoff system"
data = {}
